### ISSUE TITLE
could you please tell me how to install htmltab?

### ISSUE THREAD

**Issue by LiXingguangBrandonStark** [jmcastagnetto/bnonews-reinfection-covid19#1]
install.packages(htmltab)
Error in install.packages : object 'htmltab' not found

**Comment by jmcastagnetto** [comment]
You should not use the issues as a general help forum.

Please, do read the examples in the help info for that command, and use quotes as shown:

```
>?install.packages
```

**Comment by LiXingguangBrandonStark** [comment]
thanks, install.packages("htmltab")
Warning in install.packages :
  package ‘htmltab’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
>
